name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Buildozer in Docker Container
        run: |
          docker run \
            --volume "$(pwd):/home/user/app" \
            --workdir "/home/user/app" \
            kivy/buildozer:android-ndk-r25b \
            bash -c "buildozer android debug"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: pdownloader-apk
          path: bin/*.apk
